In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a1.shape

(3,)

In [6]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a2.shape

(2, 3)

In [8]:
a3 = np.array([[[1,2,3],
        [4,5,6],
        [7,8,9]],
               
        [[10,11,12],
        [13,14,15],
        [16,17,18]]
])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a2.ndim

2

In [12]:
a2.dtype

dtype('int64')

In [13]:
a2.size

6

In [14]:
import pandas as pd

df = pd.DataFrame(a2)
df

,0,1,2
0,1,2,3
1,4,5,6


In [15]:
one_value = np.ones((2,3))

In [16]:
one_value

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
zero_type = np.zeros((2,4))

In [18]:
zero_type

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
rang_array = np.arange(0,100,2)

In [20]:
rang_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [21]:
random_array = np.random.randint(0,20,size=(3,5))
random_array

array([[10, 12,  3, 18,  2],
       [17,  4,  3,  5, 14],
       [ 5,  6, 10, 18, 16]], dtype=int32)

In [24]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.96990515, 0.55383691, 0.45471753],
       [0.11639054, 0.29599799, 0.44368384],
       [0.54459961, 0.92014077, 0.78888425],
       [0.5248916 , 0.57811021, 0.21835296],
       [0.05475485, 0.17697454, 0.5585184 ]])

In [27]:
random_array3 = np.random.rand(5,3)

In [28]:
random_array3

array([[0.94650717, 0.828739  , 0.22896307],
       [0.24860019, 0.24011357, 0.99472722],
       [0.43140156, 0.01509606, 0.95085896],
       [0.43669303, 0.88680899, 0.03022597],
       [0.8430965 , 0.47370897, 0.35579922]])

In [39]:
np.random.seed(seed=1000)
random_array4 = np.random.randint(10,size=(5,3))
random_array4

array([[3, 7, 7],
       [0, 1, 0],
       [9, 8, 9],
       [4, 9, 4],
       [4, 2, 9]], dtype=int32)

In [40]:
random_array4

array([[3, 7, 7],
       [0, 1, 0],
       [9, 8, 9],
       [4, 9, 4],
       [4, 2, 9]], dtype=int32)

In [41]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 7, 8, 9], dtype=int32)

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
a3[:2:,:3,:2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

In [59]:
arr5 = np.random.randint(11,20,size=(1,3,4,5))
arr5

array([[[[19, 18, 11, 13, 14],
         [14, 18, 12, 17, 14],
         [15, 13, 19, 14, 11],
         [11, 12, 14, 15, 16]],

        [[18, 15, 13, 12, 15],
         [13, 14, 19, 14, 14],
         [18, 17, 19, 18, 17],
         [11, 15, 18, 18, 16]],

        [[19, 19, 15, 18, 16],
         [14, 12, 17, 19, 13],
         [17, 17, 18, 17, 19],
         [14, 14, 11, 15, 19]]]], dtype=int32)

In [64]:
arr5[:,:,:,:1]


array([[[[19, 18, 11, 13, 14],
         [14, 18, 12, 17, 14],
         [15, 13, 19, 14, 11],
         [11, 12, 14, 15, 16]],

        [[18, 15, 13, 12, 15],
         [13, 14, 19, 14, 14],
         [18, 17, 19, 18, 17],
         [11, 15, 18, 18, 16]],

        [[19, 19, 15, 18, 16],
         [14, 12, 17, 19, 13],
         [17, 17, 18, 17, 19],
         [14, 14, 11, 15, 19]]]], dtype=int32)

In [66]:
a1

array([1, 2, 3])

In [67]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
a1+a2

array([[2, 4, 6],
       [5, 7, 9]])

In [69]:
a1-a2

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [70]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [71]:
a1**2

array([1, 4, 9])

In [72]:
a1//a2

array([[1, 1, 1],
       [0, 0, 0]])

In [73]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [74]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [75]:
np.sum(a1)

np.int64(6)

In [76]:
np.sum(a2)

np.int64(21)

In [79]:
arr6 = np.random.random(1000000)
arr6[:1000]

array([1.60929116e-01, 4.33252795e-01, 3.21183157e-01, 5.55333144e-01,
       3.14428685e-01, 4.35496190e-01, 1.99011526e-01, 6.78489647e-01,
       4.20674239e-01, 5.02488084e-01, 2.37241191e-01, 8.68171218e-01,
       9.34752309e-02, 2.78177705e-01, 3.12848553e-01, 1.39006430e-01,
       5.69225411e-01, 3.30971278e-01, 1.43380040e-01, 5.57037943e-01,
       2.33266614e-01, 8.60611624e-01, 4.90557625e-01, 2.87534741e-01,
       2.62673179e-01, 3.85107601e-01, 9.19300142e-03, 2.37308259e-01,
       9.25726353e-01, 9.90721198e-01, 3.15792159e-01, 3.91368825e-01,
       3.97376671e-01, 3.12201154e-01, 2.22384282e-01, 7.60540681e-05,
       3.98481681e-01, 8.65761055e-01, 9.55277978e-01, 8.81653888e-01,
       5.10102512e-01, 9.52888804e-01, 3.28109957e-01, 7.14101872e-01,
       2.13720967e-01, 4.65385619e-01, 3.96353106e-01, 7.58088867e-01,
       3.99814044e-01, 1.78570793e-01, 5.64148211e-01, 6.66322847e-01,
       7.07674415e-01, 5.61776438e-01, 8.86879773e-02, 3.04809552e-01,
      

In [81]:
%timeit sum(arr6)

99.3 ms ± 2.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [83]:
%timeit np.sum(arr6)

996 μs ± 22.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
