In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [8]:
a1.shape

(3,)

In [5]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a2.shape

(2, 3)

In [13]:
a3 = np.array([[[1,2,3],
        [4,5,6],
        [7,8,9]],
               
        [[10,11,12],
        [13,14,15],
        [16,17,18]]
])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a3.shape

(2, 3, 3)

In [14]:
a2.ndim

2

In [15]:
a2.dtype

dtype('int64')

In [16]:
a2.size

6

In [19]:
import pandas as pd

df = pd.DataFrame(a2)
df

,0,1,2
0,1,2,3
1,4,5,6


In [21]:
one_value = np.ones((2,3))

In [22]:
one_value

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
zero_type = np.zeros((2,4))

In [24]:
zero_type

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
rang_array = np.arange(0,100,2)

In [28]:
rang_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [35]:
random_array = np.random.randint(0,20,size=(3,5))
random_array

array([[ 3,  9, 17, 18, 10],
       [14,  1, 14, 10,  0],
       [14, 19, 19, 17,  0]], dtype=int32)