In [163]:
#scikit -learn python machine learn library

# Introdunction to Sickit_learn (SkLearn)

## An end to end scikit-learn workflow

In [164]:
# 1. Get the data ready

import pandas as pd
heart_disease = pd.read_csv("dataset.csv")

In [165]:
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,2
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,1
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,2
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,1
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,1
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,1
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,1
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,1


In [166]:
# Create X (features matrix)
x = heart_disease.drop("target",axis=1)

# Create y(lables)
y = heart_disease["target"]

In [167]:
y

0      2
1      1
2      2
3      1
4      1
      ..
265    1
266    1
267    1
268    1
269    2
Name: target, Length: 270, dtype: int64

In [168]:
import warnings
warnings.filterwarnings("ignore")

In [169]:
# 2. Choose the right model and hyperparameter

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()

# We will keep the default hyperparamenter
clf.get_params()


{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [170]:
# 3. Fit the model to training data

from sklearn.model_selection import train_test_split

x_train, x_test,y_train, y_test = train_test_split(x,y,test_size=.2)

In [171]:
clf.fit(x_train,y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [172]:
# Make a prediction
import numpy as np

y_pred = clf.predict(x_test)

In [173]:
y_pred

array([2, 1, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2,
       2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 1, 1, 2, 1, 1, 2, 2, 1, 2])

In [174]:
# 4. Evaluate the model

clf.score(x_train,y_train)

1.0

In [175]:
clf.score(x_test,y_test)

0.8518518518518519

In [176]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.79      0.96      0.87        28
           2       0.95      0.73      0.83        26

    accuracy                           0.85        54
   macro avg       0.87      0.85      0.85        54
weighted avg       0.87      0.85      0.85        54



In [177]:
confusion_matrix(y_test,y_pred)

array([[27,  1],
       [ 7, 19]])

In [178]:
accuracy_score(y_test,y_pred)

0.8518518518518519

In [179]:
# 5. improve the model
# Try Different amont of n_estimators

np.random.seed(42)
for i in range(10,100,10):
    print(f"Trying model with {i} esimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(x_train,y_train)
    print(f"Model accouracy on test set :{clf.score(x_test,y_test)*100:.2f}%")
    print(" ")

Trying model with 10 esimators...
Model accouracy on test set :85.19%
 
Trying model with 20 esimators...
Model accouracy on test set :77.78%
 
Trying model with 30 esimators...
Model accouracy on test set :81.48%
 
Trying model with 40 esimators...
Model accouracy on test set :83.33%
 
Trying model with 50 esimators...
Model accouracy on test set :85.19%
 
Trying model with 60 esimators...
Model accouracy on test set :83.33%
 
Trying model with 70 esimators...
Model accouracy on test set :83.33%
 
Trying model with 80 esimators...
Model accouracy on test set :85.19%
 
Trying model with 90 esimators...
Model accouracy on test set :85.19%
 


In [180]:
# Save a model

import pickle

In [181]:
pickle.dump(clf,open("random_forest_model.pkl","wb"))

In [182]:
loaded_model = pickle.load(open("random_forest_model.pkl","rb"))

In [183]:
loaded_model.score(x_test,y_test)

0.8518518518518519

In [184]:
import sklearn
sklearn.show_versions()


System:
    python: 3.13.11 | packaged by Anaconda, Inc. | (main, Dec 10 2025, 21:21:58) [MSC v.1929 64 bit (AMD64)]
executable: C:\Users\Radhe\Desktop\simple_project_1\env\python.exe
   machine: Windows-10-10.0.19045-SP0

Python dependencies:
      sklearn: 1.8.0
          pip: 26.0.1
   setuptools: 80.10.2
        numpy: 2.4.2
        scipy: 1.16.3
       Cython: None
       pandas: 3.0.0
   matplotlib: 3.10.8
       joblib: 1.5.3
threadpoolctl: 3.5.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: mkl
    num_threads: 2
         prefix: mkl_rt
       filepath: C:\Users\Radhe\Desktop\simple_project_1\env\Library\bin\mkl_rt.2.dll
        version: 2025.0-Product
threading_layer: intel

       user_api: openmp
   internal_api: openmp
    num_threads: 4
         prefix: libiomp
       filepath: C:\Users\Radhe\Desktop\simple_project_1\env\Library\bin\libiomp5md.dll
        version: None

       user_api: openmp
   internal_api: openmp
    num_threads:

## 1. getting out data ready to be used with machine learing

There are main thing
1. Spilt data into features and labels X and Y
2. Filling missing values
3. Converting no-numerical values to numerical values


In [185]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,2
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,1
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,2
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,1
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,1


In [186]:
x = heart_disease.drop("target",axis=1)
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3


In [187]:
y = heart_disease["target"]
y.head()

0    2
1    1
2    2
3    1
4    1
Name: target, dtype: int64

In [188]:
# Split the data into training and test sets

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.3)

In [189]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((189, 13), (81, 13), (189,), (81,))

In [190]:
x.shape

(270, 13)

In [191]:
x.shape[0]*.70

189.0

## 1.1 Make sure it's all Numerical

In [192]:
car_sales = pd.read_csv("car_sales.csv")

In [193]:
car_sales

,Make,colour,odometer,Doors,Price
0,Toyota,Red,235234,4,34345
1,BMW,Red,234234,3,345345
2,Toyota,Yellow,574,5,78678678
3,Honda,Yellow,57,4,5576567
4,Honda,Yellow,764,3,2523525
...,...,...,...,...,...
73,BMW,White,42,5,23462
74,BMW,White,34,3,342342
75,Nissan,Black,6,6,245235
76,Toyota,Black,523,4,345235


In [194]:
len(car_sales)

78

In [195]:
car_sales.dtypes

Make          str
colour        str
odometer    int64
Doors       int64
Price       int64
dtype: object

In [210]:
# Split into X/Y
x = car_sales.drop("Price", axis= 1)
y = car_sales["Price"]

# Split into training and test
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2)

In [197]:
# # Buliding machine learning model

# from sklearn.ensemble import RandomForestRegressor

# model = RandomForestRegressor()
# model.fit(x_train,y_train)
# model.score(x_test,y_test)

In [211]:
x.head()


,Make,colour,odometer,Doors
0,Toyota,Red,235234,4
1,BMW,Red,234234,3
2,Toyota,Yellow,574,5
3,Honda,Yellow,57,4
4,Honda,Yellow,764,3


In [212]:
# Turn the categories into numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make","colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([( "one_hot",one_hot,categorical_features)],remainder="passthrough")
transformed_x = transformer.fit_transform(x)
transformed_x

array([[0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 2.35234e+05],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 2.34234e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 5.74000e+02],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 6.00000e+00],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 5.23000e+02],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 4.23400e+03]], shape=(78, 13))

In [213]:
pd.DataFrame(transformed_x)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,235234.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,234234.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,574.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,57.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,764.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,42.0
74,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,34.0
75,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,6.0
76,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,523.0


In [214]:
dummies = pd.get_dummies(car_sales[["Make","colour","Doors"]])

In [215]:
dummies

,Doors,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,colour_Black,colour_Red,colour_White,colour_Yellow
0,4,False,False,False,True,False,True,False,False
1,3,True,False,False,False,False,True,False,False
2,5,False,False,False,True,False,False,False,True
3,4,False,True,False,False,False,False,False,True
4,3,False,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...
73,5,True,False,False,False,False,False,True,False
74,3,True,False,False,False,False,False,True,False
75,6,False,False,True,False,True,False,False,False
76,4,False,False,False,True,True,False,False,False


In [217]:
# model.score(x_test,y_test)

## 1.2 What if there were missing values ?

    1. Fill them with some value
    2. Remove the samples with missing data altogether

In [218]:
car_sell_missing = pd.read_csv("car_sales_missing_data.csv")

In [219]:
car_sell_missing

,Make,colour,odometer,Doors,Price
0,Toyota,Red,235234.0,4.0,34345.0
1,BMW,Red,234234.0,3.0,345345.0
2,Toyota,Yellow,574.0,5.0,78678678.0
3,Honda,Yellow,57.0,4.0,5576567.0
4,Honda,Yellow,764.0,3.0,2523525.0
...,...,...,...,...,...
73,BMW,White,42.0,5.0,23462.0
74,BMW,NaN,34.0,3.0,342342.0
75,Nissan,Black,6.0,6.0,NaN
76,Toyota,Black,523.0,4.0,345235.0


In [220]:
car_sell_missing.isna().sum()

Make        0
colour      8
odometer    9
Doors       8
Price       6
dtype: int64

In [225]:
# Creating x and y

x = car_sell_missing.drop("Price",axis=1)
y = car_sell_missing["Price"]


In [239]:
## Option 1 : Fill Misiing data with pandas
car_sell_missing["Make"].fillna("missing",inplace=True)

# file the colour column
car_sell_missing["colour"].fillna("missing",inplace=True)

car_sell_missing["odometer"].fillna(car_sell_missing["odometer"].mean(),inplace=True)
car_sell_missing["Doors"].fillna(4,inplace=True)

0     4.0
1     3.0
2     5.0
3     4.0
4     3.0
     ... 
73    5.0
74    3.0
75    6.0
76    4.0
77    3.0
Name: Doors, Length: 78, dtype: float64

In [240]:
car_sell_missing.isna().sum()

Make        0
colour      8
odometer    9
Doors       8
Price       6
dtype: int64

In [242]:
car_sell_missing.dropna(inplace=True)

In [243]:
car_sell_missing.isna().sum()

Make        0
colour      0
odometer    0
Doors       0
Price       0
dtype: int64

In [244]:
len(car_sell_missing)

51

In [246]:
x = car_sell_missing.drop("Price",axis=1)
y = car_sell_missing["Price"]

In [247]:
# Let's try convert data to number


from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make","colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([( "one_hot",one_hot,categorical_features)],remainder="passthrough")
transformed_x = transformer.fit_transform(x)
transformed_x


array([[0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00,
        0.00000e+00, 0.00000e+00, 2.35234e+05],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 2.34234e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00,
        1.00000e+00, 0.00000e+00, 5.74000e+02],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 1.00000e+00,
        0.00000e+00, 0.00000e+00, 5.70000e+01],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 0.00000e+00,
        0.00000e+00, 0.00000e+00, 7.64000e+02],
       [0.00000e+00, 1.00000e+

In [248]:
pd.DataFrame(transformed_x)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,235234.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,234234.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,574.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,57.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,764.0
5,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3523.0
6,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,423.0
7,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,42.0
8,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,34.0
9,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,6.0


## Option 2 : Fill Missing Value with sikitlearn